### PR TITLE
display error messages with same status code only once

### LINKED ISSUE #94: have to click 5 error boxes away before logging in

### PR DESCRIPTION
**Pull request by v1r0x**
Fix #94 
Tried to fix issue #95 as well, but couldn't figure out how to tell the ui-router plugin to reload the page (controllers and services). I tried `$state.go('spacialist', {}, { reload: true });` and `$state.reload('spacialist');`. Maybe we have to fix it different...

### CODE REVIEW

**Comment by v1r0x** [comment]
Please review @eScienceCenter/spacialists

**Comment by v1r0x** [comment]
We could display an error message above or below the login form instead of a popup. Of course only if the error is one of (user_not_found, token_expired, token_invalid, token_absent, token_not_provided). Thus, the user could still see the reason why they have to login again, but we could get rid of the popup.

**Comment by derntl** [comment]
Yes that would be okay, although I don't think it is needed. In any case, I think;
* instead of alert-danger, I would use alert-info class.  
* No popup window
* Use non-tech language, avoid the use of the word "token". A typical end user will not care about auth tokens. Instead of "token not provided" a message could be "You are not logged in. Please log in." , or instead of "token expired" the message should be "Your login has expired. Please log in again."

**Comment by v1r0x** [comment]
I replaced the popup window with an infobox below the login form. I (tried to) replace(d) the lumen error messages with less techy ones. They can be found [here](https://github.com/eScienceCenter/Spacialist/blob/login-fix/app.js#L628-L634). Feel free to edit them.

Please review again @derntl

**Pull request merged**
