### PR TITLE
Bugfixing and enhancements

### PR DESCRIPTION
**Pull request by v1r0x**
This started as a small bugfix branch, but had to add a couple of other fixes and enhancements.
Here's a short list of things which didn't work (because they were buggy or not implemented);

1. Add markers using the leaflet panel
2. Add/Remove source entries
3. Store dimensions/epochs
4. Removed unnecessary dummy elements and other small UI enhancements
5. Open datepicker popup
6. Store data not only in the database but local as well (no refresh of the site after adding/editing/removing data from an element)

Please review and give your feedback **ASAP** or merge.
@dirkseidensticker @derntl @AngusLeBoeuf 
Thanks in advance!

### CODE REVIEW

**Comment by dirkseidensticker** [comment]
Testing revealed one issue within the sources/literature-window:
* Adding literature doesn't work (no error message in the console)
* the button for adding additional references is not active either)

**Comment by v1r0x** [comment]
>     Adding literature doesn't work (no error message in the console)
>     the button for adding additional references is not active either

Adding literature works fine for me. Could you enable the Network tab in e.g. firefox' dev console? Maybe there is an error in a GET or POST request.

The button is only active if you've selected a literature and entered a text.

**Comment by dirkseidensticker** [comment]
Thanks for verification. Works as it should. I wasn't aware that it's necessary to enter a text as well. Sorry for the hold up.

**Comment by v1r0x** [comment]
We should add an information text that it is necessary to add a text or allow adding literature without text.

**Comment by dirkseidensticker** [comment]
Yeah, that would be helping. I'll add it to our ToDo's. Cheers

**Pull request merged**
