### PR TITLE
Add Layer Control

### LINKED ISSUE #239: Unable to create Points [Geodata]
### Steps to reproduce
1. Create new point-object in map-view

### Expected behaviour
New point should be created

### Actual behaviour
Error: `$points must contain at least two entries`

This error message can be traced back to: `/lumen/vendor/phaza/laravel-postgis/src/Geometries/PointCollection.php` Line 23-24 (see as well [PointCollection.php#L23](https://github.com/njbarrett/laravel-postgis/blob/master/src/Geometries/PointCollection.php#L23))

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Lumen Version:**

**Spacialist version:**

**List of activated modules:**
<details>
<summary>Module List</summary>
</details>

**Are you using external storage, if yes which one:** local/ftp/aws/...

### Client configuration
**Browser:**

**Operating system:**

#### Webserver error log
<details>
<summary>Webserver error log</summary>
```
Insert your webserver log here
```
</details>

#### Lumen log (lumen/storage/lumen.log)
<details>
<summary>Lumen log</summary>

```
[2017-06-12 11:44:36] lumen.ERROR: InvalidArgumentException: $points must contain at least two entries in /var/www/html/spacialist/oasen/lumen/vendor/phaza/laravel-postgis/src/Geometries/PointCollection.php:24
Stack trace:
#0 /var/www/html/spacialist/oasen/lumen/app/Http/Controllers/ContextController.php(665): Phaza\LaravelPostgis\Geometries\PointCollection->__construct(Array)
#1 [internal function]: App\Http\Controllers\ContextController->addGeodata(Object(Illuminate\Http\Request))
#2 /var/www/html/spacialist/oasen/lumen/vendor/illuminate/container/Container.php(508): call_user_func_array(Array, Array)
#3 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(743): Illuminate\Container\Container->call(Array, Array)
#4 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(709): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#5 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(683): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\ContextController), 'addGeodata', Array)
#6 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(645): Laravel\Lumen\Application->callControllerAction(Array)
#7 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(625): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#8 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 /var/www/html/spacialist/oasen/lumen/vendor/tymon/jwt-auth/src/Http/Middleware/RefreshToken.php(40): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/html/spacialist/oasen/lumen/vendor/illuminate/pipeline/Pipeline.php(137): Tymon\JWTAuth\Http\Middleware\RefreshToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /var/www/html/spacialist/oasen/lumen/vendor/tymon/jwt-auth/src/Http/Middleware/Authenticate.php(32): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/html/spacialist/oasen/lumen/vendor/illuminate/pipeline/Pipeline.php(137): Tymon\JWTAuth\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /var/www/html/spacialist/oasen/lumen/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(626): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#21 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(529): Laravel\Lumen\Application->handleFoundRoute(Array)
#22 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(783): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#23 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(535): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#24 /var/www/html/spacialist/oasen/lumen/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(476): Laravel\Lumen\Application->dispatch(NULL)
#25 /var/www/html/spacialist/oasen/lumen/public/index.php(28): Laravel\Lumen\Application->run()
#26 {main}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by v1r0x**
Refs #198, fix #239 

I implemented most of the requirements of #198. The GIS-View should be implemented in a future PR, so we can have a basic working "GIS".
Beside that the order of the layers can not be changed (The Layers are implemented as object `{}` which is not sortable. There is an Angular/Leaflet-Plugin which converts it to an array `[]`, reoders and convert it back to an object. But this only works as long as Angular "sorts" objects based on the time they have been added and not based on their alphabetical order (as Angular did in the past) or anything else.).
Snapping is buggy, see #198 for more infos.
Please review and share your thoughts @eScienceCenter/spacialists

### CODE REVIEW

**Comment by v1r0x** [comment]
> Contexttype layers must define a geodata type -- where is this defined?

In the Data Model Editor (Create new Context-Type)

> After changed layer color and then refreshed page, the changed color is still stored in the layer, but the old color is used on the map.

Color works for me (except for layers which are set to not visible, see next item)

> The layer's visible/invisible setting does not seem to have any effect, or I do not understand when it will have an effect

It looks like that layers with `visible: false` are not added to the map's `eachLayer` function. Thus all geodata objects of an invisible layer are added to the `unlinked` layer.

> I cannot draw polygons or lines on the map.

Works for me.

> I am not allowed to link a polygon to a layer that allows multipolygons, which feels weird.

I'm not sure what should be the intended behaviour. I thought that QGIS only allows layers with either polygons or multipolygons. Maybe @dirkseidensticker or @AngusLeBoeuf can help?

> (this is not specific to this PR, but still:) When I click a marker on the map and the correxsponding element is displayed in the form, I do not know what kind of context type I am seeing. It would be helpful to show this, I guess, for instance the "Properties" in the heading of the properties form could be replaced by the context type.

We had the context-type behind the _Properties_ or something like that (I think _Properties_ was the heading and the context name and context-type the smaller grey part) and you ( @dirkseidensticker @derntl and @AngusLeBoeuf ) decided that it is unnecessary. If you three agree on a solution I can change it accordingly.

> I inadvertently deleted a layer in the layer editor ("Lukanien"). What effect does this have in the DB? Since there is no "New Layer" function, I guess the delete function is obsolete there as well, because the layer's existence is linked to its context type anyway?

Every context-type has it's own layer. But beside that you can create (currently not, forgot to implement the add function) new layers and  delete them (it is not possible to delete the context-type layers, since they are created/deleted by Spacialist). After a look at the DB it looks like the layer _Lukanien_ is removed.

> The up/down controls in the base layer list do not work.

Forgot to remove them from the baselayer list as well. Due to the layer structure in Leaflet it is not possible to move them around.

**Comment by derntl** [comment]
> Contexttype layers must define a geodata type -- where is this defined?
> In the Data Model Editor (Create new Context-Type)

ok, but the allowed geodata type for a layer are not shown anywhere. can this info be put somewhere

> It looks like that layers with visible: false are not added to the map's eachLayer function. Thus all geodata objects of an invisible layer are added to the unlinked layer.

Is this good or bad? i.e. does it need to be fixed?

> I'm not sure what should be the intended behaviour. I thought that QGIS only allows layers with either polygons or multipolygons. Maybe @dirkseidensticker or @AngusLeBoeuf can help?

Well in my simple world a polygon should be equivalent to a multipolygon with 1 polygon included. Only the label is different. I would find it hard to believe that one would ever want to *force* a user to enter a multipolygon (in the literal meaning of multiple polygons).

> We had the context-type behind the Properties or something like that (I think Properties was the heading and the context name and context-type the smaller grey part) and you ( @dirkseidensticker @derntl and @AngusLeBoeuf ) decided that it is unnecessary. If you three agree on a solution I can change it accordingly.

I must have had a temporary stroke when I agreed to removing this info. It is certainly far more relevant than the label "Properties". Please get it back.

**Comment by v1r0x** [comment]
> ok, but the allowed geodata type for a layer are not shown anywhere. can this info be put somewhere

Should be possible

> Is this good or bad? i.e. does it need to be fixed?

This is worse than bad....But I don't know how to fix it.

> Well in my simple world a polygon should be equivalent to a multipolygon with 1 polygon included. Only the label is different. I would find it hard to believe that one would ever want to force a user to enter a multipolygon (in the literal meaning of multiple polygons).

Yes, but we introduced the restrictions to the layers because of QGIS. If QGIS only allows Polygons **or** MultiPolygons, we should do the same.

> I must have had a temporary stroke when I agreed to removing this info. It is certainly far more relevant than the label "Properties". Please get it back.

I don't know if you agreed, but this time I'll definitely won't rework/add/remove/... anything if you three don't find a consensus.

**Comment by derntl** [comment]
> Yes, but we introduced the restrictions to the layers because of QGIS. If QGIS only allows Polygons or MultiPolygons, we should do the same.

Vinzberger, believe me: if you define a mulitpolygon layer in QGIS, and then you draw only one polygon, then QGIS will store this one polygon encoded as a multipolygon. Anything else would be plain crazy. In Spacialist the story is different. Leaflet Draw will always deliver a `POLYGON` if you draw only one polygon, because it does not care what kind of layer we have defined in the Layer editor. This would lead to the absurd situation that you _absolutely have to_ draw multiple polygons in a multipolygon layer.

> I don't know if you agreed, but this time I'll definitely won't rework/add/remove/... anything if you three don't find a consensus.

Looking at the code it appears that the disappearance of the context type in the heading is the result of some refactoring. The code is still there but accessing nonexistent property of the current element (`typeLabel` instead of `typelabel`). I fixed this in a PR.

**Comment by v1r0x** [comment]
> Vinzberger, believe me: if you define a mulitpolygon layer in QGIS, and then you draw only one polygon, then QGIS will store this one polygon encoded as a multipolygon. Anything else would be plain crazy. In Spacialist the story is different. Leaflet Draw will always deliver a POLYGON if you draw only one polygon, because it does not care what kind of layer we have defined in the Layer editor. This would lead to the absurd situation that you absolutely have to draw multiple polygons in a multipolygon layer.

You are probably right, but I won't implement something without a definite answer from someone who has worked with QGIS.

**Comment by derntl** [comment]
[Geodaten & Layers](https://trello.com/c/sJvX4poy/146-geodaten-layers)

**Comment by v1r0x** [comment]
- [ ] Workaround for `visible: false`: Load them with `visible: true` and then hide them
- [ ] Fix #239 
- [ ] Edit mode
- [ ] Snapping?

**Comment by derntl** [comment]
We're approving this PR, and will create separate issues for the remaining problems, which do not lie at our hands. 🙏

**Pull request merged**
