### PR TITLE
Photo fixes

### LINKED ISSUE #219: Deleting of Photos doesn't work
When deleting a photo (through right click and selecting "deleting image" the following error occurs:

Error: `unlink(/var/www/html/spacialist/oasen/lumen/storage/app/images): Is a directory`

### LINKED ISSUE #220: Right-click menu within photos browser is in German even if English is selected
Even if English is selected as main language, the context menu (right-click) within the photos browser is still in German.

### PR DESCRIPTION
**Pull request by v1r0x**
Fix #219 and fix #220 

The image's contextmenu should now be translated. Deleting images should delete the db entry and the image (original and thumb) from the disk.
Please review @eScienceCenter/spacialists

### CODE REVIEW

**Comment by v1r0x** [comment]
Any error in lumen or js console? Are you really on latest commit? :wink:

**Comment by dirkseidensticker** [comment]
:thinking:  There where no errors, but while thinking about it: can I even test this on a testing VM if images are not stored on the very machine? I think that's might be the issue. Will re-check this on Tuesday.

**Comment by v1r0x** [comment]
Yes, lumen instance and data storage must be on the same machine. The `Storage` driver is configured as `local`. Maybe it is possible to mount our test server's disk as storage on your vm.

**Comment by dirkseidensticker** [comment]
Deleting worked if tested directly on the server

**Pull request merged**
